version: '3.8'
services:
  db:
    image: postgres:14.3-alpine
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=share-it
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  server:
    build: server
    image: server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SERVER_PORT=9090
      - DB_URL=jdbc:postgresql://db:5432/share-it
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  gateway:
    build: gateway
    image: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - GATEWAY_PORT=8080
      - SHAREIT_SERVER_URL=http://server:9090