CREATE TABLE IF NOT EXISTS user_table (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    user_email VARCHAR(512) NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (user_email)
);

CREATE TABLE IF NOT EXISTS item_table (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    item_desc VARCHAR(255) NOT NULL,
    item_owner_id BIGINT NOT NULL,
    item_is_available BOOLEAN,
    CONSTRAINT PK_ITEM PRIMARY KEY (item_id),
    CONSTRAINT FK_USER FOREIGN KEY (item_owner_id)
        REFERENCES user_table(user_id)
        ON DELETE CASCADE
);

CREATE TYPE IF NOT EXISTS booking_status_enum AS ENUM ('WAITING', 'REJECTED', 'APPROVED');

CREATE TABLE IF NOT EXISTS booking_table (
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    booking_item_id BIGINT NOT NULL,
    booking_booker_id BIGINT NOT NULL,
    booking_start_date TIMESTAMP NOT NULL,
    booking_end_date TIMESTAMP NOT NULL,
    booking_status booking_status_enum NOT NULL,
    CONSTRAINT PK_BOOKING PRIMARY KEY (booking_id),
    CONSTRAINT FK_BOOKER FOREIGN KEY (booking_booker_id)
        REFERENCES user_table(user_id)
        ON DELETE CASCADE,
    CONSTRAINT FK_ITEM FOREIGN KEY (booking_item_id)
            REFERENCES item_table(item_id)
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comment_table (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment_text VARCHAR(512) NOT NULL,
    comment_item_id BIGINT NOT NULL,
    comment_author_id BIGINT NOT NULL,
    comment_created_date TIMESTAMP NOT NULL,
    CONSTRAINT PK_COMMENT PRIMARY KEY (comment_id),
    CONSTRAINT FK_COMMENTED_ITEM FOREIGN KEY (comment_item_id)
            REFERENCES item_table(item_id)
            ON DELETE CASCADE,
    CONSTRAINT FK_COMMENT_AUTHOR FOREIGN KEY (comment_author_id)
            REFERENCES user_table(user_id)
            ON DELETE CASCADE
);